import 'package:bbm_tracking/model/bensin_m.dart';
import 'package:flutter/material.dart';

List<BensinModel> listBensin = [
  BensinModel(
    id: 1,
    value: "pertalite",
    text: "Pertalite",
    perusahaan: "Pertamina",
    harga: 10000,
  ),
  BensinModel(
    id: 2,
    value: "pertamax",
    text: "Pertamax",
    perusahaan: "Pertamina",
    harga: 12400,
  ),
  BensinModel(
    id: 3,
    value: "pertamax_turbo",
    text: "Pertamax Turbo",
    perusahaan: "Pertamina",
    harga: 14000,
  ),
  BensinModel(
    id: 4,
    value: "pertamina_dex",
    text: "Pertamina Dex",
    perusahaan: "Pertamina",
    harga: 13550,
  ),
  BensinModel(
    id: 5,
    value: "dexlite",
    text: "Dexlite",
    perusahaan: "Pertamina",
    harga: 13150,
  ),
  BensinModel(
    id: 6,
    value: "solar",
    text: "Solar",
    perusahaan: "Pertamina",
    harga: 6800,
  ),
  BensinModel(
    id: 7,
    value: "shell_v_power_nitro",
    text: "Shell V-Power Nitro+",
    perusahaan: "Shell",
    harga: 14120,
  ),
  BensinModel(
    id: 8,
    value: "shell_v_power",
    text: "Shell V-Power",
    perusahaan: "Shell",
    harga: 13780,
  ),
  BensinModel(
    id: 9,
    value: "shell_super",
    text: "Shell Super",
    perusahaan: "Shell",
    harga: 12920,
  ),
  BensinModel(
    id: 10,
    value: "shell_v_power_diesel",
    text: "Shell V-Power Diesel",
    perusahaan: "Shell",
    harga: 13590,
  ),
  BensinModel(
    id: 11,
    value: "shell_diesel_extra",
    text: "Shell Diesel Extra",
    perusahaan: "Shell",
    harga: 13160,
  ),
  BensinModel(
    id: 12,
    value: "revvo_90",
    text: "Revvo 90",
    perusahaan: "Revvo",
    harga: 11200,
  ),
  BensinModel(
    id: 13,
    value: "revvo_92",
    text: "Revvo 92",
    perusahaan: "Revvo",
    harga: 12400,
  ),
  BensinModel(
    id: 14,
    value: "revvo_95",
    text: "Revvo 95",
    perusahaan: "Revvo",
    harga: 13200,
  ),
];
